"""add specialization to mentors

Revision ID: 308fda524b8c
Revises: 137e806cae77
Create Date: 2026-01-25 15:10:38.663121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '308fda524b8c'
down_revision: Union[str, Sequence[str], None] = '137e806cae77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentors', sa.Column('specialization', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mentors', 'specialization')
    # ### end Alembic commands ###
